"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Copy, Plus, QrCode, Trash2 } from "lucide-react";

import { deleteTable, saveTable } from "@/app/admin/actions";
import { Button, Card, EmptyState, Input, Label } from "@/components/ui";

export interface AdminTable {
  id: string;
  label: string;
  qrSlug: string;
  seats: number | null;
  isActive: boolean;
}

/**
 * Tables and their QR links.
 *
 * The QR image is generated by a public chart service at print time rather
 * than stored: a table's URL never changes, so there is nothing to keep in
 * sync, and no image-generation dependency to ship.
 */
export function TablesManager({
  tables,
  baseUrl,
}: {
  tables: AdminTable[];
  baseUrl: string;
}) {
  const router = useRouter();
  const [pending, startTransition] = React.useTransition();
  const [label, setLabel] = React.useState("");
  const [seats, setSeats] = React.useState("");
  const [copied, setCopied] = React.useState<string | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  const add = () => {
    const trimmed = label.trim();
    if (!trimmed) return;

    setError(null);
    startTransition(async () => {
      const result = await saveTable({
        label: trimmed,
        seats: seats ? Number(seats) : null,
      });
      if (result.ok) {
        setLabel("");
        setSeats("");
        router.refresh();
      } else {
        setError(result.error);
      }
    });
  };

  const copy = async (slug: string) => {
    const url = `${baseUrl}/t/${slug}`;
    try {
      await navigator.clipboard.writeText(url);
      setCopied(slug);
      window.setTimeout(() => setCopied(null), 1800);
    } catch {
      // Clipboard blocked (insecure origin, or denied): the URL is shown on
      // screen anyway, so this is a convenience, not a failure.
    }
  };

  return (
    <div className="space-y-5">
      <h1 className="font-display text-xl font-semibold text-ink">Tables</h1>

      <Card className="p-3.5">
        <div className="flex flex-wrap items-end gap-2">
          <div className="min-w-[140px] flex-1">
            <Label htmlFor="table-label">Table name</Label>
            <Input
              id="table-label"
              value={label}
              onChange={(event) => setLabel(event.target.value)}
              placeholder="Table 7"
              maxLength={40}
            />
          </div>

          <div className="w-24">
            <Label htmlFor="table-seats">Seats</Label>
            <Input
              id="table-seats"
              inputMode="numeric"
              value={seats}
              onChange={(event) => setSeats(event.target.value)}
              placeholder="4"
            />
          </div>

          <Button onClick={add} disabled={pending || !label.trim()}>
            <Plus className="h-4 w-4" />
            Add
          </Button>
        </div>

        {error && (
          <p role="alert" className="mt-2 text-sm text-danger">
            {error}
          </p>
        )}
      </Card>

      {tables.length === 0 ? (
        <EmptyState
          icon={<QrCode className="h-10 w-10" />}
          title="No tables yet"
          hint="Add a table to get a QR code customers can scan. Orders from that code arrive tagged with the table."
        />
      ) : (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {tables.map((table) => {
            const url = `${baseUrl}/t/${table.qrSlug}`;

            return (
              <Card key={table.id} className="p-3.5">
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0">
                    <p className="font-display font-semibold text-ink">
                      {table.label}
                    </p>
                    {table.seats ? (
                      <p className="text-xs text-ink-faint">
                        {table.seats} seats
                      </p>
                    ) : null}
                  </div>

                  <button
                    type="button"
                    disabled={pending}
                    onClick={() =>
                      startTransition(async () => {
                        await deleteTable(table.id);
                        router.refresh();
                      })
                    }
                    aria-label={`Delete ${table.label}`}
                    className="flex h-8 w-8 items-center justify-center rounded-full text-ink-faint hover:text-danger"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>

                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={`https://api.qrserver.com/v1/create-qr-code/?size=240x240&margin=8&data=${encodeURIComponent(url)}`}
                  alt={`QR code for ${table.label}`}
                  width={240}
                  height={240}
                  loading="lazy"
                  className="mx-auto my-3 h-36 w-36 rounded-lg bg-white p-1.5"
                />

                <button
                  type="button"
                  onClick={() => void copy(table.qrSlug)}
                  className="flex w-full items-center justify-center gap-1.5 rounded-lg bg-surface-2 px-2 py-2 text-xs text-ink-muted transition-colors hover:text-ink"
                >
                  <Copy className="h-3.5 w-3.5" />
                  {copied === table.qrSlug ? "Copied" : "Copy link"}
                </button>

                <p className="mt-1.5 truncate text-center text-[0.68rem] text-ink-faint">
                  /t/{table.qrSlug}
                </p>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
